### ISSUE TITLE
Link leads to incorrect page.

### ISSUE THREAD

**Issue by garrett-wood** [MicrosoftDocs/EMDocs#199]
Bottom link on page:

https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-govt-service-description#ems-offers-for-us-government-and-office-365-interoperability

claims to lead to Microsoft 365 Government but actually leads to main commercial EMS page.

https://docs.microsoft.com/enterprise-mobility-security/

Is the below link intended?

https://www.microsoft.com/en-US/microsoft-365/government

**Comment by dougeby** [comment]
@garrett-wood. Thanks for the feedback! I have fixed the link in the article.
