### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/EMDocs#96]
the link in Step 3 that points to info about Automated data classification is broken.

**Comment by computeronix** [comment]
appears to be working Step 3 points to: https://blogs.technet.microsoft.com/enterprisemobility/2015/06/17/bring-your-own-app-with-azure-ad-self-service-saml-configuration-now-in-preview/

However: in Additional Resources
SaaS Application List (with integration capabilities)
https://aadappgallery.azurewebsites.net/M

No longer works - here is a potential fix with this URL https://aadappgallery.azurewebsites.net/Default.aspx?Microsoft_Integrated_Synchronization=on

**Comment by computeronix** [comment]
https://github.com/MicrosoftDocs/EMDocs/pull/116

**Comment by msmbaldwin** [comment]
This was fixed. Thank you!
